name: voicenotes_ai
description: "Transform your spoken ideas into perfectly organized notes and tasks with VoiceNotes AI, the smart cross-platform app that listens, transcribes in any language, and intuitively structures your thoughts so you never miss a beat."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  path_provider: ^2.0.0
  record: '>=5.1.2'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  flutter_riverpod: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.3
  speech_to_text: ^7.0.0
  just_audio: ^0.9.43
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  whisper_flutter_new: ^1.0.1
  add_2_calendar: ^3.0.1
  share_plus: ^10.1.4
  pdf: ^3.11.1
  flutter_quill: ^11.5.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  wakelock_plus: ^1.2.8
  flutter_secure_storage: ^10.0.0
  local_auth: ^2.3.0
  crypto: ^3.0.6
  home_widget: ^0.9.0
  archive: ^4.0.0
  encrypt: ^5.0.3
  file_picker: ^8.0.0
  sentry_flutter: ^9.14.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/logo.png
  remove_alpha_ios: true
