import 'package:uuid/uuid.dart';
import '../models/folder.dart';
import 'hive_service.dart';

/// Repository for Folder CRUD operations against Hive.
class FoldersRepository {
  static const _uuid = Uuid();

  /// Get all folders, sorted by update date (newest first).
  List<Folder> getAllFolders() {
    final folders = HiveService.foldersBox.values.toList();
    folders.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
    return folders;
  }

  /// Get a single folder by ID.
  Folder? getFolderById(String id) {
    try {
      return HiveService.foldersBox.values.firstWhere((f) => f.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Create a new folder.
  Future<Folder> createFolder({
    required String name,
    bool isAutoGenerated = false,
    List<String>? topics,
  }) async {
    final folder = Folder(
      id: _uuid.v4(),
      name: name,
      isAutoGenerated: isAutoGenerated,
      topics: topics,
    );
    await HiveService.foldersBox.put(folder.id, folder);
    return folder;
  }

  /// Update an existing folder.
  Future<void> updateFolder(Folder folder) async {
    folder.updatedAt = DateTime.now();
    await HiveService.foldersBox.put(folder.id, folder);
  }

  /// Delete a folder by ID.
  Future<void> deleteFolder(String id) async {
    await HiveService.foldersBox.delete(id);
  }

  /// Add a note ID to a folder.
  Future<void> addNoteToFolder(String folderId, String noteId) async {
    final folder = getFolderById(folderId);
    if (folder != null && !folder.noteIds.contains(noteId)) {
      folder.noteIds.add(noteId);
      folder.updatedAt = DateTime.now();
      await HiveService.foldersBox.put(folder.id, folder);
    }
  }

  /// Remove a note ID from a folder.
  Future<void> removeNoteFromFolder(String folderId, String noteId) async {
    final folder = getFolderById(folderId);
    if (folder != null) {
      folder.noteIds.remove(noteId);
      folder.updatedAt = DateTime.now();
      await HiveService.foldersBox.put(folder.id, folder);
    }
  }

  /// Get total count of folders.
  int get count => HiveService.foldersBox.length;
}
