import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/folder.dart';
import '../services/folders_repository.dart';

/// Provider for the FoldersRepository singleton.
final foldersRepositoryProvider = Provider<FoldersRepository>((ref) {
  return FoldersRepository();
});

/// Notifier that manages the list of all folders, backed by Hive.
class FoldersNotifier extends Notifier<List<Folder>> {
  @override
  List<Folder> build() {
    return ref.read(foldersRepositoryProvider).getAllFolders();
  }

  void refresh() {
    state = ref.read(foldersRepositoryProvider).getAllFolders();
  }

  Future<Folder> addFolder({
    required String name,
    bool isAutoGenerated = false,
    List<String>? topics,
  }) async {
    final repo = ref.read(foldersRepositoryProvider);
    final folder = await repo.createFolder(
      name: name,
      isAutoGenerated: isAutoGenerated,
      topics: topics,
    );
    state = [...state, folder];
    return folder;
  }

  Future<void> updateFolder(Folder folder) async {
    await ref.read(foldersRepositoryProvider).updateFolder(folder);
    state = [
      for (final f in state)
        if (f.id == folder.id) folder else f,
    ];
  }

  Future<void> deleteFolder(String id) async {
    await ref.read(foldersRepositoryProvider).deleteFolder(id);
    state = state.where((f) => f.id != id).toList();
  }

  Future<void> restoreFolder(String id) async {
    await ref.read(foldersRepositoryProvider).restoreFolder(id);
    refresh();
  }

  Future<void> permanentlyDeleteFolder(String id) async {
    await ref.read(foldersRepositoryProvider).permanentlyDeleteFolder(id);
  }

  List<Folder> getTrashedFolders() {
    return ref.read(foldersRepositoryProvider).getTrashedFolders();
  }

  Future<int> purgeExpiredTrash() async {
    return ref.read(foldersRepositoryProvider).purgeExpiredTrash();
  }

  Future<void> addNoteToFolder(String folderId, String noteId) async {
    await ref.read(foldersRepositoryProvider).addNoteToFolder(folderId, noteId);
    refresh();
  }

  Future<void> removeNoteFromFolder(String folderId, String noteId) async {
    await ref
        .read(foldersRepositoryProvider)
        .removeNoteFromFolder(folderId, noteId);
    refresh();
  }

  Future<void> addProjectToFolder(String folderId, String projectId) async {
    await ref.read(foldersRepositoryProvider).addProjectToFolder(folderId, projectId);
    refresh();
  }

  Future<void> removeProjectFromFolder(String folderId, String projectId) async {
    await ref.read(foldersRepositoryProvider).removeProjectFromFolder(folderId, projectId);
    refresh();
  }
}

/// Provider for the folders list.
final foldersProvider =
    NotifierProvider<FoldersNotifier, List<Folder>>(FoldersNotifier.new);
