import 'package:flutter_riverpod/flutter_riverpod.dart';

/// State for a folder/conversation grouping.
/// Will be replaced with Hive model in Step 3.
class FolderState {
  final String id;
  final String name;
  final bool isAutoGenerated;
  final List<String> topics;
  final List<String> noteIds;
  final DateTime createdAt;
  final DateTime updatedAt;

  const FolderState({
    required this.id,
    required this.name,
    this.isAutoGenerated = false,
    this.topics = const [],
    this.noteIds = const [],
    required this.createdAt,
    required this.updatedAt,
  });

  FolderState copyWith({
    String? name,
    List<String>? topics,
    List<String>? noteIds,
    DateTime? updatedAt,
  }) {
    return FolderState(
      id: id,
      name: name ?? this.name,
      isAutoGenerated: isAutoGenerated,
      topics: topics ?? this.topics,
      noteIds: noteIds ?? this.noteIds,
      createdAt: createdAt,
      updatedAt: updatedAt ?? DateTime.now(),
    );
  }
}

/// Notifier that manages the list of all folders.
class FoldersNotifier extends Notifier<List<FolderState>> {
  @override
  List<FolderState> build() => [];

  void addFolder(FolderState folder) {
    state = [...state, folder];
  }

  void updateFolder(FolderState updated) {
    state = [
      for (final folder in state)
        if (folder.id == updated.id) updated else folder,
    ];
  }

  void deleteFolder(String id) {
    state = state.where((f) => f.id != id).toList();
  }

  void addNoteToFolder(String folderId, String noteId) {
    state = [
      for (final folder in state)
        if (folder.id == folderId)
          folder.copyWith(
            noteIds: [...folder.noteIds, noteId],
            updatedAt: DateTime.now(),
          )
        else
          folder,
    ];
  }

  void removeNoteFromFolder(String folderId, String noteId) {
    state = [
      for (final folder in state)
        if (folder.id == folderId)
          folder.copyWith(
            noteIds: folder.noteIds.where((id) => id != noteId).toList(),
            updatedAt: DateTime.now(),
          )
        else
          folder,
    ];
  }
}

/// Provider for the folders list.
final foldersProvider =
    NotifierProvider<FoldersNotifier, List<FolderState>>(FoldersNotifier.new);
