import 'package:hive/hive.dart';

part 'folder.g.dart';

@HiveType(typeId: 4)
class Folder extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  final bool isAutoGenerated;

  @HiveField(3)
  List<String> topics;

  @HiveField(4)
  List<String> noteIds;

  @HiveField(5)
  final DateTime createdAt;

  @HiveField(6)
  DateTime updatedAt;

  @HiveField(7, defaultValue: false)
  bool isDeleted;

  @HiveField(8)
  DateTime? deletedAt;

  Folder({
    required this.id,
    required this.name,
    this.isAutoGenerated = false,
    List<String>? topics,
    List<String>? noteIds,
    DateTime? createdAt,
    DateTime? updatedAt,
    this.isDeleted = false,
    this.deletedAt,
  })  : topics = topics ?? [],
        noteIds = noteIds ?? [],
        createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();
}
