import 'package:hive/hive.dart';

part 'folder.g.dart';

@HiveType(typeId: 4)
class Folder extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  final bool isAutoGenerated;

  @HiveField(3)
  List<String> topics;

  @HiveField(4)
  List<String> noteIds;

  @HiveField(5)
  final DateTime createdAt;

  @HiveField(6)
  DateTime updatedAt;

  @HiveField(7, defaultValue: false)
  bool isDeleted;

  @HiveField(8)
  DateTime? deletedAt;

  @HiveField(9)
  List<String> projectDocumentIds;

  Folder({
    required this.id,
    required this.name,
    this.isAutoGenerated = false,
    List<String>? topics,
    List<String>? noteIds,
    List<String>? projectDocumentIds,
    DateTime? createdAt,
    DateTime? updatedAt,
    this.isDeleted = false,
    this.deletedAt,
  })  : topics = topics ?? [],
        noteIds = noteIds ?? [],
        projectDocumentIds = projectDocumentIds ?? [],
        createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();

  Map<String, dynamic> toMap() => {
        'id': id,
        'name': name,
        'isAutoGenerated': isAutoGenerated,
        'topics': topics,
        'noteIds': noteIds,
        'projectDocumentIds': projectDocumentIds,
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
        'isDeleted': isDeleted,
        'deletedAt': deletedAt?.toIso8601String(),
      };

  factory Folder.fromMap(Map<String, dynamic> m) => Folder(
        id: m['id'] as String,
        name: m['name'] as String,
        isAutoGenerated: m['isAutoGenerated'] as bool? ?? false,
        topics: List<String>.from(m['topics'] as List? ?? []),
        noteIds: List<String>.from(m['noteIds'] as List? ?? []),
        projectDocumentIds: List<String>.from(m['projectDocumentIds'] as List? ?? []),
        createdAt: DateTime.parse(m['createdAt'] as String),
        updatedAt: DateTime.parse(m['updatedAt'] as String),
        isDeleted: m['isDeleted'] as bool? ?? false,
        deletedAt: m['deletedAt'] != null ? DateTime.parse(m['deletedAt'] as String) : null,
      );
}
